### ISSUE TITLE
[Feature]: Add color to kind's text, not just icon

### ISSUE THREAD

**Issue by nullchilly** [Bekaboo/dropbar.nvim#18]
### Problem

Currently the winbar fg rely on the `WinBar` highlight group

![image](https://github.com/Bekaboo/dropbar.nvim/assets/56817415/f7cd0f3a-45cd-4322-bd81-95c460672b92)

This makes it hard to add dropbar.nvim integration to colorscheme. If I change the `WinBar` highlight to make dropbar prettier, vanilla user will not be happy.

### Expected behavior

Add `DropBarNormal = { link = "WinBar", default = true }` so colorscheme can add dropbar integration easier:

![image](https://github.com/Bekaboo/dropbar.nvim/assets/56817415/eab05706-4cb7-455a-8b23-c0ffe8b9d561)

Add `color_mode` to show color for kind's text and not just its color, via `DropBarKindFunction` highlight group instead of just for icon (`DropBarIconKindFunction`)

![image](https://github.com/Bekaboo/dropbar.nvim/assets/56817415/dae10f18-609f-4598-8e42-5a610e987e41)

**Comment by Bekaboo** [comment]
This is a good idea, but I hesitate to implement this since currently the text color depends on not only `hl-WinBar` but also `hl-WinBarNC`, which make it possible to highlight texts in winbars of non-current windows in a different colors.

If I set the highlights groups explicitly and link it to `hl-WinBar` by default, we will no longer respect `hl-WinBarNC`.

Any thoughts?

**Comment by nullchilly** [comment]
I guess we can make `DropBarNormal` an empty highlight group by default

```
vim.o.winbar="%#DropBarNormal# dropbar.lua"
```

**Comment by Bekaboo** [comment]
Looks good  will look into it later.

**Comment by nullchilly** [comment]
@Bekaboo Special thanks :)

I implemented it in https://github.com/catppuccin/nvim/pull/499

**Comment by Bekaboo** [comment]
👍🏼 Good job! I'm always impressed by how configurable and aesthetic `catppuccin` is.
