### ISSUE TITLE
[Feature]: Better keyboard navigation for the menu

### ISSUE THREAD

**Issue by bellini666** [Bekaboo/dropbar.nvim#3]
### Problem

Hi,

First of all, awesome plugin! :)

Currently the menu navigation with the keyboard lacks some QOL improvements, like the possibility to go back in the menu or select another menu without having to close and open the menu again.

### Expected behavior

My suggestions:

1) Map `Left arrow` to go back in a submenu to its parent. Injecting a "previous" item as the first child could be useful as well
2) Map `Right arrow` to enter a submenu (would act like a `<CR>` when the option has children)
3) Provide mappings to easily navigate between component indexes. Maybe `<Tab>`/`<S-Tab>`?
4) For a better experience, make the selection select the whole item instead of being a cursor in the menu, just like a `cmp` menu entry. Probably required for navigation with arrows and making 1 and 2 work

With the current API I imagine that I could probably create my own mappings for 2 and 3, but I could not find a way to do 1, and 4 probably requires more internal work

**Comment by Bekaboo** [comment]
For 1 & 2:

```lua
			require("dropbar").setup({
				menu = {
					keymaps = {
						["<Left>"] = "<C-w>c",
						["<Right>"] = function()
							local menu = require("dropbar.api").get_current_dropbar_menu()
							if not menu then
								return
							end
							local cursor = vim.api.nvim_win_get_cursor(menu.win)
							local component = menu.entries[cursor[1]]:first_clickable(cursor[2])
							if component then
								menu:click_on(component, nil, 1, "l")
							end
						end,
					},
				},
			})
```

For 3: map it yourself

For 4: please clarify

**Comment by bellini666** [comment]
> For 1 & 2:

Yeah. My suggestion was to maybe consider making it a builtin mapping in the plugin if it makes sense

> For 3: map it yourself

Sure, this is only a [suggestion](https://github.com/Bekaboo/dropbar.nvim/issues/4#issuecomment-1569077853), which you might agree or not, for what IMHO would be a nice QOL improvement to have builtin.

> For 4: please clarify

[Screencast from 2023-05-30 17-56-37.webm](https://github.com/Bekaboo/dropbar.nvim/assets/134025/afcc161a-5fea-4eef-b798-515b7204771a)

When I navigate with arrow keys, I would expect to instead of having a cursor that can be moved inside the items, it would instead highlight the whole item, as just moving the cursor has no real "value", specially when using `<Left>`/`<Right>` (the reason why I suggested giving them some utility)

**Comment by Bekaboo** [comment]
OK I understand. Please let me explain why I'm not going to map `<Left>` and `<Right>` by default:

There are currently actually two clickable components in one row of the menu (there can be more if you write your own source and provide > 2 components in a row), the first one is the indicator shown is the current symbol has children, and clicking or hitting Enter on it will open a sub-menu for its children; the second component is the symbol itself and clicking/hitting Enter on it will directly brings you to the start of its range. So there's differences if you click on the different parts in the same row (entry) in the drop-down menu, that why I cannot make it default because some users might want to use `<Left>` or `<Right>` to navigate to the correctly component then hit Enter. 

> When I navigate with arrow keys, I would expect to instead of having a cursor that can be moved inside the items, it would instead highlight the whole item, as just moving the cursor has no real "value", specially when using <Left>/<Right> (the reason why I suggested giving them some utility)

Makes sense to me, will look into it in the future 👍🏼

**Comment by gennaro-tedesco** [comment]
I am trying to implement some of the above suggestions by myself but I would like some help, if possible: for example for 

> 3. Provide mappings to easily navigate between component indexes. Maybe <Tab>/<S-Tab>?

I am doing
```lua
keymaps = {
	["<Tab>"] = function()
		local api = require("dropbar.api")
		local menu = api.get_current_dropbar_menu()
		if menu then
			return api.goto_context_start(1)
		end
	end,
}
```
or should one use `get_dropbar_menu(win: integer)` passing the "next" window number instead?

Thank you for the awesome plugin!

**Comment by Bekaboo** [comment]
@gennaro-tedesco The description of `goto_context_start()` might be misleading, I will try to make it clear later, but this function is expected to be called inside a window that has `dropbar.nvim` attached because what it do is getting the current dropbar and set the cursor position according to the ranges of the symbols in the dropbar, which is apparently not the case when your cursor is inside a menu window that has no winbar at all.

> assign a key to exit the dropbar menu altogether

What you want to do is using `menu.prev_menu` repeatedly to traverse the linked list until you get the root menu (a menu without `prev_menu`), then close that root menu `menu:close()`.

> Is there an api function that brings back the focus to the initial vim buffer instead?

Will work on a new api function on this since I can see it is not trivial for users to create such function themselves.

**Comment by Bekaboo** [comment]
@gennaro-tedesco @bellini666 

Now you can use any key in the drop-down menu that moves your cursor horizontally (`l`, `h`, `w`, `e`, `b`, `<Left>`, `<Right>`, etc) to directly jump to the nearest previous/next clickable component. To disable this feature, set `opts.menu.quick_navigation` to` false`.

**Comment by gennaro-tedesco** [comment]
Thank you for your work and effort! I have updated the plugin, however I cannot seem to have the expected behaviour, and any of the motions you mentioned seem to still just move the cursor horizontally within the "string" of the drop-down menu _unless_ when at the boundary (in which case it goes to the previous or next menu item in the dropdown, accordingly).

As you said, it should be enabled by default? I have also explicitly set `opts.menu.quick_navigation` to `true` to no avail.

**Comment by Bekaboo** [comment]
@gennaro-tedesco 

Using the builtin sources, by default there are five areas in a single menu entry:

![image](https://github.com/Bekaboo/dropbar.nvim/assets/76579810/b88caa95-adde-4171-9b8c-a3dcccccbd64)

1. left padding
2. indicator (clickable symbol)
3. separator (unclickable symbol, set to empty space by default)
4. the symbol representing some context information in the source buffer (clickable)
5. right padding

Given the layout above, the expected behavior is:

- If your cursor is in `1`
    - moving left will not trigger `quick_navigation` because there's no
      clickable symbol on the left
    - moving right will trigger `quick_navigation` and set the cursor to the
      beginning of `2`
- If your cursor is in `2`
    - moving left will not trigger `quick_navigation` because there's no
      clickable symbol on the left
    - moving right will trigger `quick_navigation` and set the cursor to the
      beginning of `4`
- If your cursor is in `3`
    - moving left will trigger `quick_navigation` and set the cursor to the
      beginning of `2`
    - moving right will trigger `quick_navigation` and set the cursor to the
      beginning of `4`
- If your cursor is in `4`
    - moving left will trigger `quick_navigation` and set the cursor to the
      beginning of `2`
    - moving right will not trigger `quick_navigation` because there's no
      clickable symbol on the right
- If your cursor is in `5`
    - moving left will trigger `quick_navigation` and set the cursor to the
      beginning of `4`
    - moving right will not trigger `quick_navigation` because there's no
      clickable symbol on the right

Does this matches the behavior on your end? If not, or you have suggestions about improving `quick_navigation`, please let me know.

**Comment by gennaro-tedesco** [comment]
Yes, it does match the behaviour! I apologise, there was a misunderstanding from my side: I had thought that the feature would move across menus, in your examples from H2 --> H3 --> H2 --> README.md, but I understand now it is meant to move across areas in a menu entry instead!

**Comment by Maldus512** [comment]
> I am trying to implement some of the above suggestions by myself but I would like some help, if possible: for example for
> 
> > 3. Provide mappings to easily navigate between component indexes. Maybe `<Tab>/<S-Tab>`?
> 
> I am doing
> 
> ```lua
> keymaps = {
>   ["<Tab>"] = function()
>     local api = require("dropbar.api")
>     local menu = api.get_current_dropbar_menu()
>     if menu then
>       return api.goto_context_start(1)
>     end
>   end,
> }
> ```
> 
> or should one use `get_dropbar_menu(win: integer)` passing the "next" window number instead?
> 

Sorry, I can't seem to make this work. I'd like to create a mapping to move between components in the dropbar after having opened a submenu. I could simply call `pick` with the index if I knew what the current index is. Is there a way to set a key binding to move between component menus?
