### ISSUE TITLE
[Feature]: Option to ignore .gitignore files on path source

### ISSUE THREAD

**Issue by bellini666** [Bekaboo/dropbar.nvim#4]
### Problem

Currently the path source fills everything it finds, including files/folders that the dev usually don't want to see

### Expected behavior

It would be nice to have an option to automatically filter .gitignore files out.

Maybe having an alternative source that uses `git ls` or even `fd` (which also ignores `.gitignore) to list the files?

**Comment by Bekaboo** [comment]
Please, read the doc before asking, it is clearly documented [here](https://github.com/Bekaboo/dropbar.nvim#path), use `opts.sources.path.filter` to filter out files or directories you don't want to see

**Comment by bellini666** [comment]
> Please, read the doc before asking, it is clearly documented [here](https://github.com/Bekaboo/dropbar.nvim#path), use `opts.sources.path.filter` to filter out files or directories you don't want to see

Yes, I know. I did read the doc before asking and I know that I can implement it myself. The _feature request_ I opened was regarding the possibility of adding a builtin way of doing that, specially for something not so trivial like this and with possibly performance implications, and not asking for help on "how to do that".

Also, a small advise: Replying like that to users giving feedback on your lib and/or trying to contribute in some way will only push them back. If you don't like/agree with the feature request, a simple "Sorry, but I don't want extra options/sources for files so you will have to use `opts.sources.path.filter` yourself" and closing the issue would be enough. You attract more bees with honey than vinegar, you know?

**Comment by Bekaboo** [comment]
Sorry, but I didn't see your reply until just now, there are just too many emails from this repository.

So let's be clear about this: if you want a new source, just state it clearly in the title "I want a new source that gets files/directories from the output of `git ls` / `fd` / ...", be straightforward, instead of saying that you want to ignore a single file from the path source, which will simply make me think that you are not reading the document because the `opts.sources.path.filter` function just fits perfectly for this purpose and only a person who does not read the doc will open an issue with this title -- and I don't think it is a offensive behavior to remind users to read the doc.

> Replying like that to users giving feedback on your lib and/or trying to contribute in some way will only push them back

Contributions are always welcome, either in the way of pull requests or bug report/feature request. I try be objective to every user that enjoy this plugin and accept those contributions that makes sense to me -- as you can see I accepts your suggestion in another feature request issue.

**Comment by Bekaboo** [comment]
> Try to understand why the "Please, read the doc before asking, it is clearly documented [here](https://github.com/Bekaboo/dropbar.nvim#path)" could be offensive to you if you got that response in another repository, specially if you did already read the docs and the issue has nothing to do with you not doing that.

Then I can only feel sorry if you are offended by this please-read-the-doc request, I will try be more careful next time when talking to person with a sensitive heart.

I'm not replying this issue in the future. Please understand that everyone's time is precious and instead of criticizing an open source maintainer who devotes his spare time in making this plugin asking nothing for return and continuing this meaningless conversion, you and me both have more important things to do.

**Comment by bellini666** [comment]
> Then I can only feel sorry if you are offended by this please-read-the-doc request, I will try be more careful next time when talking to person with a sensitive heart.

I can see that text interpretation as a whole is not your strong suit, and also who has the "sensitive heart" and got offended by a friendly advice ;)

> Please understand that everyone's time is precious and instead of criticizing an open source maintainer who devotes his spare time in making this plugin asking nothing for return and continuing this meaningless conversation, you and me both have more important things to do.

Again, if you properly interpreted my first reply of this "meaningless conversation" you would see that I'm in no way criticizing you, but instead giving you a friendly advice of how your reply code be misread in an offensive way and push contributions back, specially considering that you posted this on reddit and said for users to "feel free to open an issue if you find any bugs or have any suggestions".

I'm also a author/maintainer of some open source libs, and I deal daily with a lot of issues/PRs in my spare time. Been doing that for almost 13 years now.

> I'm not replying this issue in the future

Np! The advice was given, take it or ignore it, there's indeed nothing more else to say.
